package constants;

public enum PopupInfo {

	UNKNOWN_KOREAN(0),
	MINIMAP(1),
	QUESTS(2),
	INVENTORY(3),
	ATTACKING(4),
	ITEM_PICKUP(5),
	EQUIPING_ITEMS(6),
	SKILL_WINDOW(7),
	QUICK_SLOTS(8),
	BREAKABLE_CONTAINERS(9),
	CHAIR_EREVE(10),
	WORLD_MAP_EREVE(11),
	QUEST_HELPER(12),
	STATS_WINDOW(13),
	USING_ITEMS(14),
	SKILL_WINDOW_2(15),
	EQUIPING_ITEMS_2(16),
	QUICK_SLOTS_2(17),
	BREAKABLE_CONTAINERS_2(18),
	CHAIR_ARAN(19),
	ATTACKING_2(20),
	ITEM_PICKUP_2(21),
	BREAKABLE_CONTAINERS_ADVENTURER(22),
	MINIMAP_ADVENTURER(25),
	WORLD_MAP_MAPLE_ISLAND(26),
	CHAIR_ADVENTURER(27),
	USING_ITEMS_ADVENTURER(28),
	EQUIPING_ITEMS_ADVENTURER(29),
	QUEST_HELPER_ADVENTURER(31),
	QUEST_WINDOW_ADVENTURER(32);
	
	
	private final int id;
	
	PopupInfo(int id) {
		this.id = id;
	}
	
	public String getPath(){
		return "UI/tutorial.img/"+id;
	}
	
	
}
