package constants;

import lombok.Getter;

public enum Song {
	
	Jukebox_Congratulation("Jukebox/Congratulation"),
	Bgm00_SleepyWood("Bgm00/SleepyWood"),
	Bgm00_FloralLife("Bgm00/FloralLife"),
	Bgm00_GoPicnic("Bgm00/GoPicnic"),
	Bgm00_Nightmare("Bgm00/Nightmare"),
	Bgm00_RestNPeace("Bgm00/RestNPeace"),
	Bgm01_AncientMove("Bgm01/AncientMove"),
	Bgm01_MoonlightShadow("Bgm01/MoonlightShadow"),
	Bgm01_WhereTheBarlogFrom("Bgm01/WhereTheBarlogFrom"),
	Bgm01_CavaBien("Bgm01/CavaBien"),
	Bgm01_HighlandStar("Bgm01/HighlandStar"),
	Bgm01_BadGuys("Bgm01/BadGuys"),
	Bgm02_MissingYou("Bgm02/MissingYou"),
	Bgm02_WhenTheMorningComes("Bgm02/WhenTheMorningComes"),
	Bgm02_EvilEyes("Bgm02/EvilEyes"),
	Bgm02_JungleBook("Bgm02/JungleBook"),
	Bgm02_AboveTheTreetops("Bgm02/AboveTheTreetops"),
	Bgm03_Subway("Bgm03/Subway"),
	Bgm03_Elfwood("Bgm03/Elfwood"),
	Bgm03_BlueSky("Bgm03/BlueSky"),
	Bgm03_Beachway("Bgm03/Beachway"),
	Bgm03_SnowyVillage("Bgm03/SnowyVillage"),
	Bgm04_PlayWithMe("Bgm04/PlayWithMe"),
	Bgm04_WhiteChristmas("Bgm04/WhiteChristmas"),
	Bgm04_UponTheSky("Bgm04/UponTheSky"),
	Bgm04_ArabPirate("Bgm04/ArabPirate"),
	Bgm04_ShininHarbor("Bgm04/Shinin'Harbor"),
	Bgm04_WarmRegard("Bgm04/WarmRegard"),
	Bgm05_WolfWood("Bgm05/WolfWood"),
	Bgm05_DownToTheCave("Bgm05/DownToTheCave"),
	Bgm05_AbandonedMine("Bgm05/AbandonedMine"),
	Bgm05_MineQuest("Bgm05/MineQuest"),
	Bgm05_HellGate("Bgm05/HellGate"),
	Bgm06_FinalFight("Bgm06/FinalFight"),
	Bgm06_WelcomeToTheHell("Bgm06/WelcomeToTheHell"),
	Bgm06_ComeWithMe("Bgm06/ComeWithMe"),
	Bgm06_FlyingInABlueDream("Bgm06/FlyingInABlueDream"),
	Bgm06_FantasticThinking("Bgm06/FantasticThinking"),
	Bgm07_WaltzForWork("Bgm07/WaltzForWork"),
	Bgm07_WhereverYouAre("Bgm07/WhereverYouAre"),
	Bgm07_FunnyTimeMaker("Bgm07/FunnyTimeMaker"),
	Bgm07_HighEnough("Bgm07/HighEnough"),
	Bgm07_Fantasia("Bgm07/Fantasia"),
	Bgm08_LetsMarch("Bgm08/LetsMarch"),
	Bgm08_ForTheGlory("Bgm08/ForTheGlory"),
	Bgm08_FindingForest("Bgm08/FindingForest"),
	Bgm08_LetsHuntAliens("Bgm08/LetsHuntAliens"),
	Bgm08_PlotOfPixie("Bgm08/PlotOfPixie"),
	Bgm09_DarkShadow("Bgm09/DarkShadow"),
	Bgm09_TheyMenacingYou("Bgm09/TheyMenacingYou"),
	Bgm09_FairyTale("Bgm09/FairyTale"),
	Bgm09_FairyTalediffvers("Bgm09/FairyTalediffvers"),
	Bgm09_TimeAttack("Bgm09/TimeAttack"),
	Bgm10_Timeless("Bgm10/Timeless"),
	Bgm10_TimelessB("Bgm10/TimelessB"),
	Bgm10_BizarreTales("Bgm10/BizarreTales"),
	Bgm10_TheWayGrotesque("Bgm10/TheWayGrotesque"),
	Bgm10_Eregos("Bgm10/Eregos"),
	Bgm11_BlueWorld("Bgm11/BlueWorld"),
	Bgm11_Aquarium("Bgm11/Aquarium"),
	Bgm11_ShiningSea("Bgm11/ShiningSea"),
	Bgm11_DownTown("Bgm11/DownTown"),
	Bgm11_DarkMountain("Bgm11/DarkMountain"),
	Bgm12_AquaCave("Bgm12/AquaCave"),
	Bgm12_DeepSee("Bgm12/DeepSee"),
	Bgm12_WaterWay("Bgm12/WaterWay"),
	Bgm12_AcientRemain("Bgm12/AcientRemain"),
	Bgm12_RuinCastle("Bgm12/RuinCastle"),
	Bgm12_Dispute("Bgm12/Dispute"),
	Bgm13_CokeTown("Bgm13/CokeTown"),
	Bgm13_Leafre("Bgm13/Leafre"),
	Bgm13_MinarsDream("Bgm13/Minar'sDream"),
	Bgm13_AcientForest("Bgm13/AcientForest"),
	Bgm13_TowerOfGoddess("Bgm13/TowerOfGoddess"),
	Bgm14_DragonLoad("Bgm14/DragonLoad"),
	Bgm14_HonTale("Bgm14/HonTale"),
	Bgm14_CaveOfHontale("Bgm14/CaveOfHontale"),
	Bgm14_DragonNest("Bgm14/DragonNest"),
	Bgm14_Ariant("Bgm14/Ariant"),
	Bgm14_HotDesert("Bgm14/HotDesert"),
	Bgm15_MureungHill("Bgm15/MureungHill"),
	Bgm15_MureungForest("Bgm15/MureungForest"),
	Bgm15_WhiteHerb("Bgm15/WhiteHerb"),
	Bgm15_Pirate("Bgm15/Pirate"),
	Bgm15_SunsetDesert("Bgm15/SunsetDesert"),
	Bgm16_Duskofgod("Bgm16/Duskofgod"),
	Bgm16_FightingPinkBeen("Bgm16/FightingPinkBeen"),
	Bgm16_Forgetfulness("Bgm16/Forgetfulness"),
	Bgm16_Remembrance("Bgm16/Remembrance"),
	Bgm16_Repentance("Bgm16/Repentance"),
	Bgm16_TimeTemple("Bgm16/TimeTemple"),
	Bgm17_MureungSchool1("Bgm17/MureungSchool1"),
	Bgm17_MureungSchool2("Bgm17/MureungSchool2"),
	Bgm17_MureungSchool3("Bgm17/MureungSchool3"),
	Bgm17_MureungSchool4("Bgm17/MureungSchool4"),
	Bgm18_BlackWing("Bgm18/BlackWing"),
	Bgm18_DrillHall("Bgm18/DrillHall"),
	Bgm18_QueensGarden("Bgm18/QueensGarden"),
	Bgm18_RaindropFlower("Bgm18/RaindropFlower"),
	Bgm18_WolfAndSheep("Bgm18/WolfAndSheep"),
	Bgm19_BambooGym("Bgm19/BambooGym"),
	Bgm19_CrystalCave("Bgm19/CrystalCave"),
	Bgm19_MushCatle("Bgm19/MushCatle"),
	Bgm19_RienVillage("Bgm19/RienVillage"),
	Bgm19_SnowDrop("Bgm19/SnowDrop"),
	Bgm20_GhostShip("Bgm20/GhostShip"),
	Bgm20_NetsPiramid("Bgm20/NetsPiramid"),
	Bgm20_UnderSubway("Bgm20/UnderSubway"),
	Bgm21_2021year("Bgm21/2021year"),
	Bgm21_2099year("Bgm21/2099year"),
	Bgm21_2215year("Bgm21/2215year"),
	Bgm21_2230year("Bgm21/2230year"),
	Bgm21_2503year("Bgm21/2503year"),
	Bgm21_KerningSquare("Bgm21/KerningSquare"),
	Bgm21_KerningSquareField("Bgm21/KerningSquareField"),
	Bgm21_KerningSquareSubway("Bgm21/KerningSquareSubway"),
	Bgm21_TeraForest("Bgm21/TeraForest"),
	BgmEvent_FunnyRabbit("BgmEvent/FunnyRabbit"),
	BgmEvent_FunnyRabbitFaster("BgmEvent/FunnyRabbitFaster"),
	BgmEvent_wedding("BgmEvent/wedding"),
	BgmEvent_weddingDance("BgmEvent/weddingDance"),
	BgmEvent_wichTower("BgmEvent/wichTower"),
	BgmGL_amoria("BgmGL/amoria"),
	BgmGL_Amorianchallenge("BgmGL/Amorianchallenge"),
	BgmGL_chapel("BgmGL/chapel"),
	BgmGL_cathedral("BgmGL/cathedral"),
	BgmGL_Courtyard("BgmGL/Courtyard"),
	BgmGL_CrimsonwoodKeep("BgmGL/CrimsonwoodKeep"),
	BgmGL_CrimsonwoodKeepInterior("BgmGL/CrimsonwoodKeepInterior"),
	BgmGL_GrandmastersGauntlet("BgmGL/GrandmastersGauntlet"),
	BgmGL_HauntedHouse("BgmGL/HauntedHouse"),
	BgmGL_NLChunt("BgmGL/NLChunt"),
	BgmGL_NLCtown("BgmGL/NLCtown"),
	BgmGL_NLCupbeat("BgmGL/NLCupbeat"),
	BgmGL_PartyQuestGL("BgmGL/PartyQuestGL"),
	BgmGL_PhantomForest("BgmGL/PhantomForest"),
	BgmJp_Feeling("BgmJp/Feeling"),
	BgmJp_BizarreForest("BgmJp/BizarreForest"),
	BgmJp_Hana("BgmJp/Hana"),
	BgmJp_Yume("BgmJp/Yume"),
	BgmJp_Bathroom("BgmJp/Bathroom"),
	BgmJp_BattleField("BgmJp/BattleField"),
	BgmJp_FirstStepMaster("BgmJp/FirstStepMaster"),
	BgmMY_Highland("BgmMY/Highland"),
	BgmMY_KualaLumpur("BgmMY/KualaLumpur"),
	BgmSG_BoatQuay_field("BgmSG/BoatQuay_field"),
	BgmSG_BoatQuay_town("BgmSG/BoatQuay_town"),
	BgmSG_CBD_field("BgmSG/CBD_field"),
	BgmSG_CBD_town("BgmSG/CBD_town"),
	BgmSG_Ghostship("BgmSG/Ghostship"),
	BgmUI_ShopBgm("BgmUI/ShopBgm"),
	BgmUI_Title("BgmUI/Title")
	;
	
	@Getter
	private final String id;
	
	private Song(String id) {
		this.id = id;
	}

	public static Song getById(String name) {
		
		for(Song song : values()){
			if(song.id.equalsIgnoreCase(name)){
				return song;
			}
		}
		
		return null;
	}
	
}
